# Generated by Django 2.2.3 on 2019-10-28 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField(blank=True, default=None, null=True, verbose_name='Exercise name')),
                ('number', models.IntegerField(blank=True, default=None, null=True, verbose_name='Exercise number')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=None, null=True, verbose_name='Variant name')),
                ('number', models.IntegerField(blank=True, default=None, null=True, verbose_name='Variant number')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Theme number*:')),
                ('name', models.TextField(verbose_name='Theme name*:')),
                ('content', models.TextField(verbose_name='Theme content*:')),
                ('source_name', models.TextField(blank=True, default=None, null=True, verbose_name='Source name:')),
                ('source_link', models.URLField(blank=True, default=None, null=True, verbose_name='Source link:')),
                ('reference1_name', models.TextField(blank=True, default=None, null=True, verbose_name='Reference 1:')),
                ('reference1_link', models.URLField(blank=True, default=None, null=True, verbose_name='Link 1:')),
                ('reference2_name', models.TextField(blank=True, default=None, null=True, verbose_name='Reference 2:')),
                ('reference2_link', models.URLField(blank=True, default=None, null=True, verbose_name='Link 2:')),
                ('reference3_name', models.TextField(blank=True, default=None, null=True, verbose_name='Reference 3:')),
                ('reference3_link', models.URLField(blank=True, default=None, null=True, verbose_name='Link 3:')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('question_text', models.TextField()),
                ('question_answer', models.TextField()),
                ('question_type', models.IntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercise_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='oge2020.Exercise', verbose_name='Question')),
                ('theme_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='oge2020.Theme', verbose_name='Theme')),
                ('variant_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='oge2020.Variant', verbose_name='Variant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
