# Generated by Django 2.2.3 on 2019-10-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oge2020', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 1'),
        ),
        migrations.AddField(
            model_name='question',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='question',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='question',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 4'),
        ),
        migrations.AddField(
            model_name='question',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 5'),
        ),
        migrations.AddField(
            model_name='theme',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 1'),
        ),
        migrations.AddField(
            model_name='theme',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='theme',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='theme',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 4'),
        ),
        migrations.AddField(
            model_name='theme',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение 5'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Название задания'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Номер задания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exercise_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='oge2020.Exercise', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='theme_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='oge2020.Theme', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='question',
            name='variant_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='oge2020.Variant', verbose_name='Вариант'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='content',
            field=models.TextField(verbose_name='Содержание темы*:'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.TextField(verbose_name='Имя темы*:'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер темы*:'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='reference1_link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка 1:'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='reference1_name',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Пример 1:'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='reference2_link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка 2:'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='reference2_name',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Пример 2:'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='reference3_link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка 3:'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='reference3_name',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Пример 3:'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='source_link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка на источник:'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='source_name',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Название источника:'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Имя варианта'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Номер варианта'),
        ),
    ]
