# Generated by Django 2.2.3 on 2019-10-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oge2020', '0003_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='answer_document',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Документ для проверки'),
        ),
    ]
