# Generated by Django 2.2.3 on 2019-10-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oge2020', '0004_journal_answer_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='Верный ответ'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
    ]
