# Generated by Django 2.2.3 on 2019-10-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oge2020', '0005_auto_20191028_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='timestamp',
        ),
    ]
