# Generated by Django 2.2.3 on 2019-10-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oge2020', '0006_remove_journal_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='session_id',
            field=models.TextField(default='i986tfvbhju7ytfdx', verbose_name='Индивидуальный номер для объединения результатов тестирования'),
            preserve_default=False,
        ),
    ]
