# Generated by Django 2.2.3 on 2019-10-29 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oge2020', '0007_journal_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('intensive', 'Интенсивная (4 раза в неделю,обязательно решить 2 вариант в неделю )'), ('middle', 'Средняя(2 раза в неделю,обязательно решить 1 варианта в неделю)'), ('olimpiada', 'Подготовка с улубленным изучением(4 раза в неделю с олимпиадными задачами, обязательно прешить 2 варианта в неделю)')], default='intensive', max_length=30, verbose_name='Выбор режима')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
