# Generated by Django 2.2.3 on 2019-10-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oge2020', '0008_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='mode',
            field=models.CharField(choices=[('intensive', 'Интенсивная (4 раза в неделю,обязательно решить 2 вариант в неделю )'), ('middle', 'Средняя (2 раза в неделю,обязательно решить 1 варианта в неделю)'), ('olimpiada', 'Подготовка с улубленным изучением (4 раза в неделю с олимпиадными задачами, обязательно решить 2 варианта в неделю)')], default='intensive', max_length=30, verbose_name='Выбор режима'),
        ),
    ]
